# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'CRUMPET' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Digitail
  pod 'JTMaterialSpinner', '~> 3.0'
  pod 'MGSwipeTableCell'
  pod 'SideMenu', '~> 6.0.0'
  # pod 'SideMenu'
  pod 'IQKeyboardManagerSwift'
  pod 'JTAppleCalendar'
  pod 'RangeSeekSlider'

  
  target 'DigitailTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DigitailUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
