# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'CRUMPET' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Digitail
  pod 'JTMaterialSpinner', '~> 3.0'
  pod 'MGSwipeTableCell'
  pod 'SideMenu', '~> 6.0.0'
  # pod 'SideMenu'
  pod 'IQKeyboardManagerSwift'
  pod 'JTAppleCalendar'
  pod 'RangeSeekSlider'
  pod 'SOMotionDetector'
  pod 'MBProgressHUD'

  
  target 'DigitailTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DigitailUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
               end
          end
   end
end
